# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='tweetpost',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='tweet.TwitterAccount'),
        ),
    ]
